### ISSUE TITLE
RuntimeError: Legacy autograd function with non-static forward method is deprecated.

### ISSUE THREAD

**Issue by JWFrank** [midasklr/SSD.Pytorch#11]
When I use eval.py to evaluate my training result, it will show this error message as below

Finished loading model!
Traceback (most recent call last):
  File "eval.py", line 443, in <module>
    thresh=args.confidence_threshold)
  File "eval.py", line 390, in test_net
    detections = net(x).data
  File "E:\DeltaConda\envs\SSE_AI_ENV\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\AI_Customs\SSD-Pytorch\ssd.py", line 108, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "E:\DeltaConda\envs\SSE_AI_ENV\lib\site-packages\torch\autograd\function.py", line 149, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

Did you have ever seen this problem? 
Thanks for your help

My Pytorch version is 1.6

Note that, I train SSD using my custom dataset

**Comment by wj-shin** [comment]
do you solve this problem? I also have this error

**Comment by Tareq69** [comment]
Did you solve this problem? @JWFrank  @wj-shin
