### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ariharasudhanm** [midasklr/SSD.Pytorch#16]
I have another question should I need to resize all the images to 512?
After following all the steps for custom training I am getting this error. Could you please help me to resolve this issue?

Traceback (most recent call last):
  File "train.py", line 285, in <module>
    train()
  File "train.py", line 90, in train
    parser.error('Must specify dataset if specifying dataset_root')
  File "/usr/lib/python3.8/argparse.py", line 2531, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib/python3.8/argparse.py", line 2501, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib/python3.8/argparse.py", line 2467, in format_usage
    return formatter.format_help()
  File "/usr/lib/python3.8/argparse.py", line 294, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.8/argparse.py", line 225, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 332, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "/usr/lib/python3.8/argparse.py", line 407, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range

**Comment by ksmdnl** [comment]
The input size after the preprocessing that you feed into the network has to have a fix size, 512x512 or 300x300 in the case of SSD300

**Comment by Eldad27** [comment]
@ariharasudhanm @midasklr Did you manage to solve this problem? If yes, can you kindly share?
